# Generated by Django 4.2.2 on 2023-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
