# Generated by Django 4.2.2 on 2023-06-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartMining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minner_bash', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='onoff',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
