# Generated by Django 4.2.2 on 2023-06-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_server_onoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_status', models.BooleanField(verbose_name=0)),
                ('miner_bash', models.CharField(max_length=2048)),
                ('miner_output', models.CharField(max_length=2048)),
            ],
        ),
        migrations.DeleteModel(
            name='StartMining',
        ),
    ]
