# Generated by Django 4.2.2 on 2023-06-22 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_miner_delete_startmining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='onoff',
        ),
    ]
