# Generated by Django 4.2.2 on 2023-06-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_remove_server_onoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ss58', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='HotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletname', models.CharField(max_length=255)),
                ('hotkey', models.CharField(max_length=255)),
                ('mnemonic', models.CharField(max_length=2047)),
            ],
        ),
        migrations.DeleteModel(
            name='Miner',
        ),
        migrations.AddField(
            model_name='server',
            name='miner_bash',
            field=models.CharField(default='', max_length=2047),
        ),
        migrations.AddField(
            model_name='server',
            name='miner_output',
            field=models.CharField(default='', max_length=2047),
        ),
        migrations.AddField(
            model_name='server',
            name='mining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='power',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(max_length=31),
        ),
    ]
